config {
    type: "table"
}
with base as(
SELECT
  vo.* EXCEPT(visit_start_DATE, visit_end_DATE),
  COALESCE(visit_start_DATE, visit_end_DATE) AS visit_start_DATE,
  COALESCE(visit_end_DATE, visit_start_DATE) AS visit_end_DATE
FROM
  ${ref("all_smm_patients")} patient
LEFT JOIN
  `healthtree-production.dataform.visit_occurrence` vo
ON
  patient.person_source_value = vo.person_source_value
WHERE
vo.person_source_value is not null
  ORDER BY
  person_source_value
),

date_timestamp as (
  SELECT * EXCEPT(visit_start_DATE, visit_end_DATE),
  TIMESTAMP(visit_start_DATE) as visit_start_DATE,
  TIMESTAMP(visit_end_DATE) as visit_end_DATE,
  visit_start_DATE as visit_start_prev,
  visit_end_DATE as visit_end_prev
   from base
)

SELECT * EXCEPT(visit_start_prev, visit_end_prev,visit_concept_id,
visit_start_DATETIME, visit_end_DATETIME, visit_type_concept_id, provider_id,provider_source_value,
care_site_id,visit_source_concept_id, admitting_source_concept_id, discharge_to_concept_id,
preceding_visit_occurrence_id)
FROM date_timestamp
WHERE visit_start_DATE IS NULL

ORDER BY person_source_value, visit_start_DATE
