config {
    type: "view"
}

SELECT
  DISTINCT
  person_source_value
FROM
  `healthtree-production.dataform.condition_occurrence`
WHERE
  (condition_source_concept_id in ("413587002", "273.1")
  OR (condition_source_concept_id like "D47.2" AND (LOWER(condition_source_value) like "%smoldering%"
  OR LOWER(condition_source_value) like "%smm%")))
  AND person_source_value NOT IN
  (
    SELECT userId FROM `healthtree-production.HT.users` WHERE (email LIKE '%healthtree.org%' AND email NOT LIKE "jenny@healthtree.org")
    OR email LIKE '%deleted.com%'
  )
  AND (condition_start_DATE IS NOT NULL OR condition_end_DATE IS NOT NULL)
GROUP BY
  person_source_value