
SELECT person_source_value,
TIMESTAMP(MIN(condition_start_DATE)) as smm_first_DATE,
TIMESTAMP(MAX(condition_end_DATE)) as smm_last_DATE
 FROM ${ref("diagnostic")} d
 WHERE d.person_source_value in (SELECT person_source_value from ${ref("all_smm_patients")})
 AND
 (
    LOWER(condition_source_value) LIKE "%smoldering%"
    OR LOWER(condition_source_value) like "%smm%"
    OR SAFE_CAST(condition_source_code AS STRING) = "413587002"
 )
 GROUP BY person_source_value
 ORDER BY TIMESTAMP_DIFF(MAX(condition_end_DATE), MIN(condition_start_DATE), DAY) DESC
